### ISSUE TITLE
Italian UI translations

### ISSUE THREAD

**Issue by delucis** [gabrielemercolino/cardano-introduzione-web-dev#1]
Hi @gabrielemercolino — exciting to see you using Starlight!

I noticed you translated the UI to Italian — https://github.com/gabrielemercolino/cardano-introduzione-web-dev/blob/master/src/content/i18n/it-IT.json — and wondered if you'd be interested in submitting a PR to add these to the main Starlight repository for others to be able to use? It would mainly mean copying your file as `it.json` to this directory: https://github.com/withastro/starlight/tree/main/packages/starlight/translations

Would love to be able to support Italian for everyone out-of-the-box.

Don't hesitate to let us know if you have any questions or feature ideas as you try out Starlight. We'd be happy to hear them!

**Comment by gabrielemercolino** [comment]
Hi, thank you for reaching me.

I'm happy to see

**Comment by gabrielemercolino** [comment]
Hi, thank you for reaching me.

I'm happy to see my little work is appreciated. I'm going to submit it for sure 😀!

**Comment by delucis** [comment]
Thanks again for the contribution! Will close this issue 💜
